name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version: 'stable'
      - name: go fmt
        run: test -z $(gofmt -l .)
      - name: go vet
        run: go vet
      - name: staticcheck
        uses: dominikh/staticcheck-action@v1
        with:
          version: 'latest'
          install-go: false
      - name: go test
        run: go test
