name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: go fmt
        run: test -z $(gofmt -l .)
      - name: go vet
        run: go vet
      - name: go test
        run: go test
