name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version: 'stable'
      - name: go fmt
        run: test -z $(gofmt -l .)
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61
      - name: go test
        run: go test
